- 통계 vs 데이터분석 vs 머신러닝
    - 데이터분석: **문제를 정의하고 인사이트 도출** [고객 구매 패턴 분석]
    - 통계: 데이터를 **요약, 해석하는 수학** [평균, 분산]
    - 머신러닝: 데이터를 학습하여 **예측** [스팸함 분류, 추천]

- 데이터분석: 데이터를 분석하여 의사결정에 도움을 준다.
    - 의사결정 데이터 기반의 근거
    - 패턴 발견, 예측(머신러닝)

- DA Flow (흐름)
    1. 문제 정의
    1. **데이터 수집**
    1. **데이터 정제(결측, 이상치 처리)**
    1. **탐색 - 시각화 - 통계분석 및 해석**(평균, 분포, 상관관계, 막대그래프, 히스토그램)
    1. 결론 도출

- 시트 vs DB vs Python
    - 시트는 편함. # 밀키트
    - DB는 대용량 CRUD (억단위) # 대용량 냉장고
    - 파이썬 시각화, 분석, 머신러닝 # 요리

- 라이브러리
    - `numpy` : 빠름(배열 연산) `파이썬 리스트 vs Numpy 배열 차이점`
    - `pandas` : 표(DataFrame) -> `numpy` 기반으로 만들어짐
    - `matplotlib` : 시각화(그래프)
    - `seaborn` : 시각화 심화
    - `scipy` : 고급 통계, 수학 연산
    - `scikit-learn` : 머신러닝

In [ ]:
%pip install numpy # 터미널대신 여기에 이렇게 적어도 됨.

In [1]:
python_list = [1, 2, 3, 4, 5]
result = [x * 2 for x in python_list]
print(result)

[2, 4, 6, 8, 10]


In [6]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
result = array * 2
print(result) # 기존의 리스트와는 다름. type도 리스트가 아님.

[ 2  4  6  8 10]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기', arr.size)

[1 2 3 4 5] <class 'numpy.ndarray'>
차원 1
형태 (5,)
크기 5


In [8]:
arr1d = np.array([1, 2, 3, 4, 5])
arr1d

array([1, 2, 3, 4, 5])

In [19]:
l2d = [
    [1, 2, 3],
    [4, 5, 6]
]
arr2d = np.array(l2d)

arr2d.ndim, arr2d.shape, arr2d.size, arr2d.dtype

(2, (2, 3), 6, dtype('int64'))

In [ ]:
# 실수형 arr
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [23]:
# 0으로 채워짐
z1d = np.zeros(5)
z2d = np.zeros((2, 3))
print(z1d, z2d)

# 1로 채워짐
o1d = np.ones(5)
o2d = np.ones((2, 3))
print(o1d, o2d)

# n으로 채움 -> 5칸, 7로 채움
n1d = np.full(5,7)
n2d = np.full((2, 3), 7)
print(n1d, n2d)

# 빈칸이지만 먼저 만듬
empty = np.empty(3)
print(empty)

[0. 0. 0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.] [[1. 1. 1.]
 [1. 1. 1.]]
[7 7 7 7 7] [[7 7 7]
 [7 7 7]]
[1. 2. 3.]


In [ ]:
# 시퀀스 데이터

# 레인지
range_arr = np.arange(0, 10, 2)
print(range_arr)

np.array(range(0, 10, 2)) # 속도면에서는 위가 훨씬 나음

# 등간격 실수 배열
lin_space = np.linspace(0, 1, 5)
print(lin_space)

# *로그스케일
log_space = np.logspace(0, 2, 5) # 10^0 ~ 10^2 5개 요소
print(log_space)



[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [56]:
# 난수 배열

# 균등 분포 난수 (0~1) 사이를 균등확률 분포
random = np.random.rand(3, 3) # 0 ~ 1 실수
print(random)

# *정규 분포 난수
normal = np.random.randn(3, 3)
print(normal)

# 정수 난수
int_random = np.random.randint(0, 10, (3, 3))
print(int_random)

# 시드 설정(랜덤 재현 가능)
np.random.seed(42) # 랜덤 상황 42 고정
np.random.rand(3)

[[0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]
[[-0.46947439  0.54256004 -0.46341769]
 [-0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112]]
[[2 6 3]
 [8 2 4]
 [2 6 4]]


array([0.37454012, 0.95071431, 0.73199394])

In [58]:
# 배열의 데이터 타입
# 데이터 타입 확인
arr = np.array([1, 2, 3])
print(arr.dtype)

# 데이터 타입 지정 생성
f_arr = np.array([1, 2, 3], dtype=np.float64)
print(f_arr.dtype)

# 데이터 타입 변경 (int -> float)
converted = arr.astype(np.float64)
print(converted.dtype)

# 문자열 -> 숫자
str_arr = np.array(['1.2', '2.3', '3.4'])
num_arr = str_arr.astype(float) # np.floatXX 라고 지정 안하고 float쓰면 -> float64
print(num_arr, num_arr.dtype)

int64
float64
float64
[1.2 2.3 3.4] float64


In [ ]:
# 메모리 사용량
print(arr.itemsize) # int64 -> 1칸에 8byte
print(converted.itemsize) # float32 -> 4byte

# 총 메모리 사용량
print(arr.nbytes) # 8byte * 3칸
print(converted.nbytes)

8
8
24
24


In [60]:
# 배열 재구성
arr = np.arange(12)
print(arr)
reshaped2d = arr.reshape(3, 4) # 3row * 4col
print(reshaped2d)

reshaped3d = arr.reshape(2, 2, 3) # 2페이지, 2row * 3col
print(reshaped3d)

# 자동계산
auto1 = arr.reshape(3, -1) # row 3개, col 알아서
auto2 = arr.reshape(-1, 6) # row 알아서, col 6개

print(auto1)
print(auto2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# 1차원 -> N차원
# reshape -> 원본 그대로, 새로운 배열 만듬
# rssize -> 원본을 바꿈

arr = np.arange(12)
reshaped = arr.reshape(3, 4) # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3, 4)  # arr 이 바뀜
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# N차원 -> 1차원
arr = np.array([[1, 2, 3], [4, 5, 6]])

r = arr.ravel() # 뷰(원본 연결) -> 빨리 펼쳐서 보기
f = arr.flatten() # 복사본 -> 안전하게 새로 만들어서 활용

r[0] = 100
f[0] = -100
print(arr)
print(r, f)

[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6] [-100    2    3    4    5    6]


In [168]:
# 전치 -> 행과 열을 교환
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

arr_2d.transpose(), arr_2d.T

[[1 2 3]
 [4 5 6]]


(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
# 1 ~ 15 정수 배열(arange vs array(range))
print(np.arange(1, 16), np.array(range(1, 16)))

# 0 ~ 9까지 홀수
print(np.arange(1, 10, 2))

# 0 ~ 3까지 균등 6등분(5구간) 배열
print(np.linspace(0, 3, 6))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 3 5 7 9]
[0.  0.6 1.2 1.8 2.4 3. ]


In [ ]:
# 4 * 4 단위 행렬(identity matrix) -> 대각선 1, 나머지 0
print(np.eye(4))

# 3 * 4 사이즈의 1로 가득찬 int 배열
np.ones((3, 4), dtype=int)

# 2 * 3 * 4 사이즈 0~1 난수 배열
np.random.rand(2, 3, 4) # 인자로 차원 지정 -> 오래된 버전에서 주로 씀
np.random.random((2, 3, 4)) # 튜플로 차원 지정 -> 최신 버전에서 주로 씀

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[[0.51423444, 0.59241457, 0.04645041, 0.60754485],
        [0.17052412, 0.06505159, 0.94888554, 0.96563203],
        [0.80839735, 0.30461377, 0.09767211, 0.68423303]],

       [[0.44015249, 0.12203823, 0.49517691, 0.03438852],
        [0.9093204 , 0.25877998, 0.66252228, 0.31171108],
        [0.52006802, 0.54671028, 0.18485446, 0.96958463]]])

# 배열의 인덱싱/슬라이싱

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# 접근
print(arr[0], arr[2], arr[-1], arr[-2])

# 변경
arr[0] = 100

print(arr)

# 추가는 불가능/ 사이즈를 늘리거나 줄이는 건 X

10 30 50 40
[100  20  30  40  50]


In [ ]:
arr_2d = np.array(range(1,10)).reshape(3, 3)

# Numpy 에서만 지원
arr_2d[0, 0] # arr_2d[0][0] -> r0, c0
arr_2d[1, 1]

arr_2d[1] # 행 접근

# 변경
arr_2d[0, 0] = 100
arr_2d

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [79]:
# 슬라이싱
arr = np.arange(10)
print(
    arr[2:5],
    arr[:5],
    arr[5:]
)

print(
    arr[1:8:2],
    arr[::2]
)

print(
    arr[::-1],
    arr[7:2:-1]
)

# 슬라이싱으로 일괄 변경(Python에선 기능 없음)
arr[3:6] = 100
print(arr)

[2 3 4] [0 1 2 3 4] [5 6 7 8 9]
[1 3 5 7] [0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0] [7 6 5 4 3]
[  0   1   2 100 100 100   6   7   8   9]


In [ ]:
# 다차원 배열 슬라이싱

arr_2d = np.arange(1, 13).reshape(3, -1)
print(arr_2d)

# row(행) 슬라이싱 -> 0, 1 idx 행
print(arr_2d[0:2])

# col(열) 슬라이싱 -> 모든 행의 idx 1, 2 열
print(arr_2d[:, 1:3])

# row / col 동시 슬라이싱 -> 1, 2 행 / 0, 1 열
print(arr_2d[1:3, 0:2])

# 간격지정 -> 행/열 모두 2간격
print(arr_2d[::2, ::2])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [92]:
# 다차원 배열 슬라이싱으로 변경
print(arr_2d)

# 부분 배열 일괄 변경
arr_2d[0:2, 0:2] = 0
print(arr_2d)

# 열 교체(모든행, idx 3열) -> 벡터 -> 교체 -> 원본 matrix 의 열이 바뀜
arr_2d[:, 3] = [100, 200, 300]

print(arr_2d)

[[  0   0   3 100]
 [  0   0   7 200]
 [  9  10  11 300]]
[[  0   0   3 100]
 [  0   0   7 200]
 [  9  10  11 300]]
[[  0   0   3 100]
 [  0   0   7 200]
 [  9  10  11 300]]


In [97]:
# boolean 인덱싱
# 조건에 따라 배열 요소 선택

arr = np.arange(1, 6)

# 마스킹 -> T/F 로 바꿈
mask = arr > 3
print(mask, arr)

# 마스킹 배열로 필터링
print(arr[mask])

# 직접 조건
print(arr[arr > 3])

# 다중 조건
print(arr[ (arr > 2) & (arr < 5)]) # and
print(arr[ (arr == 1) | (arr > 3)]) # or



[False False False  True  True] [1 2 3 4 5]
[4 5]
[4 5]
[3 4]
[1 4 5]


In [111]:
# 2차원 배열 불리언 인덱싱
arr_2d = np.arange(1, 10).reshape(3, 3)

mask = arr_2d > 5

print(arr_2d[mask]) # 원본 matrix 형태 없음. True로 필터된 애들만 Vector로 나옴.
print(arr_2d[arr_2d < 6])

# 조건에 맞는 행만 선택
row_mask = np.array([True, False, True])
print(arr_2d)
print(arr_2d[row_mask]) # row T, F, T -> 0, 2 row 만 뽑음
# arr_2d[:, 0:3:2]



[6 7 8 9]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


In [115]:
#  Fancy 인덱싱
arr = np.arange(10, 60, 10)
print(arr)
arr[1]

# arr[1, 2] -> arr[1][2] 이건 2차원에 사용하는거라 에러임
print(arr[ [1, 2] ]) # arr[1], arr[2]를 뽑아라
print(arr[ [0, 2, 3] ]) # arr[0], arr[2], arr[3]만 가져와라

print(arr[[0, 0, 1, 1, 2]])
print(arr[[4, 2, 3, 1, 1]])

[10 20 30 40 50]
[20 30]
[10 30 40]
[10 10 20 20 30]
[50 30 40 20 20]


In [119]:
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)

print(arr_2d[0]) # row 0

# 특정 행만 선택
print(arr_2d[ [0, 2] ]) # row 0, 2

# 행과 열 동시에 선택
print(
    arr_2d[ # (0, 0), (1, 2), (2, 1) 순서로 벡터 만듬
        [0, 1, 2],
        [0, 2, 1]
    ]
)

# 행렬의 열을 순서 바꾸기
print(
    arr_2d[
        :, # 모든 행
        [2, 0, 1] # 열 idx를 이렇게 바꿔라
    ]
)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2 3]
 [7 8 9]]
[1 6 8]
[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [159]:
# 10부터 20까지의 정수 배열 생성
arr = np.arange(10, 21)
print('원본', arr)

원본 [10 11 12 13 14 15 16 17 18 19 20]


In [161]:
# 문제1: 배열의 첫 번째, 세 번째, 마지막 요소 출력
print(arr[0], arr[2], arr[-1])

# 문제2: 인덱스 2부터 5까지 요소 출력
print(arr[2:6])

# 문제3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력
print(arr[:4:2])

# 문제4: 배열의 요소를 역순으로 출력
print(arr[::-1])

10 12 20
[12 13 14 15]
[10 12]
[20 19 18 17 16 15 14 13 12 11 10]


In [163]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print('원본', matrix)

원본 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [165]:
# 문제1: (1,2) 위치의 요소 출력
print(matrix[1, 2])

# 문제2: 두 번째 행 전체 출력
print(matrix[1])

# 문제3: 마지막 열 전체 출력
print(matrix[:, -1]) 

# 문제4: 첫 번째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출
print(matrix[::2, 1::2])
print(matrix[[0, 2], :][:, [1,3]])
matrix[np.ix_([0, 2], [1, 3])]

6
[4 5 6 7]
[ 3  7 11]
[[ 1  3]
 [ 9 11]]
[[ 1  3]
 [ 9 11]]


array([[ 1,  3],
       [ 9, 11]])

In [138]:
arr = np.arange(1, 21)
print('원본', arr)


원본 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [146]:
# 문제1: 5의 배수만 선택하여 출력
print(arr[arr % 5 == 0])

# 문제2: 3보다 크고 15보다 작은 요소 선택
print(arr[(arr > 3) & (arr < 15)])

# 문제3: 7의 배수이거나 홀수인 요소 선택
print(arr[(arr % 2 == 1) | (arr % 7 == 0)])

[ 5 10 15 20]
[ 4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13 14 15 17 19]


In [166]:
matrix = np.arange(1, 21).reshape(5, 4)
print('원본', matrix)

# 문제4: 10보다 큰 요소만 100으로 변경 (슬라이싱/불리언인덱싱 -> 뷰 생성(원본데이터 연결))
print(matrix[matrix > 10])
matrix[matrix > 10] = 100
print(matrix)


원본 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[11 12 13 14 15 16 17 18 19 20]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10 100 100]
 [100 100 100 100]
 [100 100 100 100]]


## 선형대수 연산
### 배열 <-> 배열 연산

In [169]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a ** 2)
print(a ** b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[    1    64  2187 65536]


In [170]:
a = np.array([True, False, True, False])
b = np.array([False, True, True, False])

# 논리연산
# AND
print(a & b)
# OR
print(a | b)
# NOT
print(~a)

[False False  True False]
[ True  True  True False]
[False  True False  True]


## 벡터(1줄) <-> 스칼라(단일값) 연산
> Broadcasting (스칼라가 배열 크기에 맞게 확장)

In [ ]:
# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 덧셈
print(arr + 10)     # [11 12 13 14 15]

# 스칼라 뺄셈
print(arr - 1)      # [0 1 2 3 4]

# 스칼라 곱셈
print(arr * 2)      # [2 4 6 8 10]

# 스칼라 나눗셈
print(arr / 2)      # [0.5 1.  1.5 2.  2.5]

# 스칼라 거듭제곱
print(arr ** 2)     # [ 1  4  9 16 25]

# 스칼라 비교 (불리언 배열)
print(arr > 3)      # [False False False  True  True]
print(arr == 2)     # [False  True False False False]

[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[False False False  True  True]
[False  True False False False]


## 매트릭스(행렬) <-> 스칼라(단일값) 연산

In [172]:
# 2차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 스칼라 연산
print(arr_2d + 10)
# [[11 12 13]
#  [14 15 16]]

print(arr_2d * 3)
# [[ 3  6  9]
#  [12 15 18]]

[[11 12 13]
 [14 15 16]]
[[ 3  6  9]
 [12 15 18]]


## 매트릭스(행렬) <-> 벡터(1줄) 연산

In [173]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# 행렬 + 행 벡터
print(matrix + vector)

# 열 벡터 브로드캐스팅
col_vec = np.array(
    [
        [100],
        [200]
    ]
)
print(matrix + col_vec)

[[11 22 33]
 [14 25 36]]
[[101 102 103]
 [204 205 206]]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print('Matrix shape', matrix.shape)
print('Vector shape', vector.shape)
# 1. Vector (3, )가 앞에 1이 추가됨 ->  Matrix (1, 3)으로 변함.
# 2. 더해야하는 matrix (2, 3)이랑 줄 수 가 같을 때까지 row 복사함.

print('Matrix + Vector')
print(matrix + vector)

Matrix shape (2, 3)
Vector shape (3,)
Matrix + Vector
[[11 22 33]
 [14 25 36]]


In [ ]:
# 브로드 캐스팅 가능한 경우 (shape 확인을 하자! 행이 맞아야 함.)

A = np.ones((3, 2))       # 3x2 배열
B = np.ones((2,))         # 길이 2인 1차원 배열 (1x2로 해석) (행벡터)
C = np.ones((3, 1))       # 3x1 배열 (사실상 열벡터)

print("A + B 형태:", (A + B).shape)  # (3, 2) - B는 각 행에 브로드캐스팅
print(A + B)


print("A + C 형태:", (A + C).shape)  # (3, 2) - C는 각 열에 브로드캐스팅
print(A + C)

A + B 형태: (3, 2)
[[2. 2.]
 [2. 2.]
 [2. 2.]]
A + C 형태: (3, 2)
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
# 차원이 다르면, 확장(브로드캐스팅) 가능

In [178]:
# 뷰(원본 데이터와 링크)와 복사본(완전 별도) 차이

arr = np.arange(1, 6)
print(arr)

# 슬라이싱 -> 뷰 생성
arr[2:4] = 100
arr

view = arr[1:4]
print(view)

view[0] = 20
print(arr)

# 복사본..?
copy = arr.copy()
copy[0] = 100
print(arr, copy)


[1 2 3 4 5]
[  2 100 100]
[  1  20 100 100   5]
[  1  20 100 100   5] [100  20 100 100   5]


In [179]:
# 연산중 데이터 자동 변환
int_arr = np.array([1, 2, 3])
float_arr = np.array([1.5, 2.5, 3.5])

# int + float = float
print(int_arr + float_arr)

# int / int = float
print(int_arr / 2)

# int // int = int
print(int_arr // 2)

[2.5 4.5 6.5]
[0.5 1.  1.5]
[0 1 1]


In [182]:
arr1 = np.array([8, 12, 6, 10])
arr2 = np.array([3, 4, 1, 20])

print(arr1 ** 2)
print(arr1 ** 0.5) # 루트와 같은 결과

# 각 자리마다 최대값만 모음
print(np.maximum(arr1, arr2))

# arr1 + arr2 의 모든 자리수를 더한 총합
print(np.sum(arr1 + arr2))

[ 64 144  36 100]
[2.82842712 3.46410162 2.44948974 3.16227766]
[ 8 12  6 20]
64


In [ ]:
# 테스트 배열
x = np.array([0, np.pi/4, np.pi/2, np.pi])
y = np.array([1, 2, 3, 4])

# 삼각함수
print("sin(x) =", np.sin(x))  # [0., 0.70710678, 1., 0.]
print("cos(x) =", np.cos(x))  # [1., 0.70710678, 0., -1.]
print("tan(x) =", np.tan(x))  # [0., 1., 16331239353195370., 0.]

# 역삼각함수
print("arcsin(sin(x)) =", np.arcsin(np.sin(x)))

# 지수와 로그
# 자연상수 e^x -> e^1, e^2, e^3
print("exp(y) =", np.exp(y))  # [2.71828183, 7.3890561, 20.08553692, 54.59815003]
# 자연상수 log e
print("log(y) =", np.log(y))  # [0., 0.69314718, 1.09861229, 1.38629436]
print("log10(y) =", np.log10(y))  # [0., 0.30103, 0.47712125, 0.60205999]
print("log2(y) =", np.log2(y))  # [0., 1., 1.58496250, 2.]

# 제곱근과 거듭제곱
print("sqrt(y) =", np.sqrt(y))  # [1., 1.41421356, 1.73205081, 2.]
print("power(y, 2) =", np.power(y, 2))  # [1, 4, 9, 16]

# 절대값과 부호
z = np.array([-2, -1, 0, 1, 2])
print("abs(z) =", np.abs(z))  # [2 1 0 1 2]
print("sign(z) =", np.sign(z))  # [-1 -1  0  1  1]

# 소수점 처리
w = np.array([1.2, 2.7, 3.5, 4.9])
print("floor(w) =", np.floor(w))  # [1. 2. 3. 4.] (내림)
print("ceil(w) =", np.ceil(w))   # [2. 3. 4. 5.] (올림)
print("round(w) =", np.round(w))  # [1. 3. 4. 5.] (반올림)
print("trunc(w) =", np.trunc(w))  # [1. 2. 3. 4.] (소수점 버림)

sin(x) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
tan(x) = [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(sin(x)) = [0.00000000e+00 7.85398163e-01 1.57079633e+00 1.22464680e-16]
exp(y) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(y) = [0.         0.69314718 1.09861229 1.38629436]
log10(y) = [0.         0.30103    0.47712125 0.60205999]
log2(y) = [0.        1.        1.5849625 2.       ]
sqrt(y) = [1.         1.41421356 1.73205081 2.        ]
power(y, 2) = [ 1  4  9 16]
abs(z) = [2 1 0 1 2]
sign(z) = [-1 -1  0  1  1]
floor(w) = [1. 2. 3. 4.]
ceil(w) = [2. 3. 4. 5.]
round(w) = [1. 3. 4. 5.]
trunc(w) = [1. 2. 3. 4.]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
])

# 기본 집계
print("합계:", np.sum(arr))          # 45
print("평균:", np.mean(arr))         # 5.0
print("최소값:", np.min(arr))        # 1
print("최대값:", np.max(arr))        # 9
print("표준편차:", np.std(arr))      # 2.581988897471611
print("분산:", np.var(arr))          # 6.666666666666667

# 축을 따라 집계
print("행별 합계:", np.sum(arr, axis=1))  # [ 6 15 24]
print("열별 합계:", np.sum(arr, axis=0))  # [12 15 18]
print("행별 평균:", np.mean(arr, axis=1))  # [2. 5. 8.]
print("열별 평균:", np.mean(arr, axis=0))  # [4. 5. 6.]
print("행별 최소값:", np.min(arr, axis=1))  # [1 4 7]
print("열별 최소값:", np.min(arr, axis=0))  # [1 2 3]

합계: 45
평균: 5.0
최소값: 1
최대값: 9
표준편차: 2.581988897471611
분산: 6.666666666666667
행별 합계: [ 6 15 24]
열별 합계: [12 15 18]
행별 평균: [2. 5. 8.]
열별 평균: [4. 5. 6.]
행별 최소값: [1 4 7]
열별 최소값: [1 2 3]
